// Single source of truth for the launcher and production build entries.
export const TOOLS = [
  { id:'preflight', name:'Publication preflight', category:'privacy',
    blurb:'Check a mixed batch of PDFs, Office files, images and text-like data for signals worth reviewing before sharing.', keywords:'publish publication preflight privacy batch check inspect files metadata comments personal data' },
  { id:'privacy-find', name:'Possible personal-data finder', category:'privacy',
    blurb:'Find common high-confidence patterns such as email, UK phone/postcode/NI, IP, URLs and card-like numbers for human review.', keywords:'privacy pii personal data email phone postcode ni card ip find scan redact' },
  { id:'pseudonymise', name:'Data pseudonymiser', category:'privacy',
    blurb:'Apply stable pseudonyms, masking, salted fingerprints or column removal to CSV/TSV data locally.', keywords:'csv tsv privacy pseudonym pseudonymise anonymise mask hash remove columns personal data' },
  { id:'office', name:'Office privacy inspector', category:'privacy',
    blurb:'Inspect and selectively clean Word, Excel and PowerPoint properties, then export a low-disclosure local inspection report.', keywords:'office docx xlsx pptx metadata author comments tracked changes privacy properties thumbnail' },
  { id:'metadata', name:'Metadata stripper', category:'privacy',
    blurb:'Remove EXIF, GPS location and author data from images before you share them. JPEG & PNG stripped losslessly.', keywords:'exif gps privacy jpeg png author metadata' },
  { id:'pdf-inspect', name:'PDF privacy inspector', category:'privacy',
    blurb:'Inspect PDF metadata and embedded features, clean Info/XMP metadata, and export a local inspection report.', keywords:'pdf privacy inspect metadata attachments forms javascript signatures clean xmp' },
  { id:'pdf-sanitise', name:'PDF sanitiser', category:'privacy',
    blurb:'Rebuild visible PDF pages into a fresh document without the original forms, links, annotations, attachments, scripts, metadata or signatures.', keywords:'pdf privacy sanitise sanitize structural clean attachments forms javascript links signatures annotations' },
  { id:'redact', name:'Redaction', category:'privacy',
    blurb:'Flatten redactions into images and PDFs so the pixels underneath are not retained.', keywords:'redact pdf image privacy black out flatten sensitive' },
  { id:'image', name:'Image converter', category:'files',
    blurb:'Convert SVG, PNG, JPEG and WebP, resize/compress one image or apply one policy to a local batch.', keywords:'image photo batch resize compress convert svg png jpeg webp zip' },
  { id:'pdf', name:'PDF workbench', category:'files',
    blurb:'Merge, extract, reorder and build PDF packs with blank/image pages, numbering, watermarks, crop boxes and form flattening.', keywords:'pdf merge split extract reorder rotate delete duplicate pages number watermark crop form flatten image blank' },
  { id:'document-markdown', name:'Document → Markdown', category:'files',
    blurb:'Convert Word, PowerPoint, spreadsheets, OpenDocument, RTF, EPUB, CSV and text-based PDFs to Markdown entirely in the browser.', keywords:'document markdown convert doc docx odt rtf epub pdf ppt pptx xls xlsx ods odp csv local wasm anydoc' },
  { id:'hash', name:'File checksum', category:'files',
    blurb:'Calculate SHA-256 fingerprints and compare files with a checksum you have been given.', keywords:'sha sha256 checksum hash fingerprint verify file' },
  { id:'secret', name:'Secret generator', category:'security',
    blurb:'Generate cryptographically secure app, session and webhook secrets in common formats, with .env and terminal equivalents.', keywords:'secret key random token env jwt session webhook hex base64 base64url uuid openssl password security' },
  { id:'csv', name:'CSV cleaner', category:'data',
    blurb:'Trim, remove empty rows or columns, deduplicate, handle common encodings and convert to JSON.', keywords:'csv excel encoding utf8 dedupe clean data json' },
  { id:'convert', name:'Data converter', category:'data',
    blurb:'Convert, prettify and validate between JSON, CSV and YAML without silently changing CSV IDs.', keywords:'json csv yaml convert validate prettify data' },
  { id:'diff', name:'Text & document diff', category:'text',
    blurb:'Compare pasted text or locally extracted TXT/Markdown, DOCX and PDF text by line, word or character.', keywords:'text document pdf docx diff compare line word character changes' },
  { id:'contrast', name:'Accessibility colour checker', category:'accessibility',
    blurb:'Check WCAG text and UI contrast, audit palettes, inspect focus colours and preview colour-vision deficiencies.', keywords:'wcag accessibility contrast colour color palette focus aa aaa vision' },
];
